### ISSUE TITLE
Allow override of proxy docker image version used for testkit integration tests

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1047]
Needing to build a local SDK as well, just to inject the local proxy snapshot version, adds some complexity. Maybe we should just have the proxy docker image tag used by the SDK testkit overridable with a system property or config? Then can use a released SDK and set the local snapshot proxy version for the integration tests. Would also make it easier to run locally like this when needed.

_Originally posted by @pvlugter in https://github.com/lightbend/kalix-proxy/pull/1539#pullrequestreview-1030963156_

Note that we already provide a way to override the proxy version introduced at #1037 for when building / releasing the SDK but not at runtime from the end-user app perspective.

**Comment by aludwiko** [comment]
For local development, it will be also nice to simply set the proxy address for IT test and launch the proxy from Main, without testcontainers.

**Comment by johanandren** [comment]
Leaving this open as a opt out of testcontainers to manually run a proxy also sounds very useful.
