### ISSUE TITLE
mvn deploy deploying to kalix should be opt in

### ISSUE THREAD

**Issue by jroper** [lightbend/kalix-jvm-sdk#1058]
I've used maven for many years, including `mvn deploy`, and I was very surprised when I learnt today that running `mvn deploy` on a Kalix project actually *runs* the software on a server.

The definition of `mvn deploy` in the [Maven documentation](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) is:

> deploy - done in the build environment, copies the final package to the remote repository for sharing with other developers and projects.

That is, it's used to deploy an artifact to an artifact repository. This is what people familiar with maven expect it to do.

There are two problems with attaching kalix deploy to this:

* Existing Maven users may accidentally do far more than they intended when they run it. Imagine a seasoned Java developer joining an existing team that's using Kalix. On the first day, they set up their kalix command, get access to the different environments, etc. Then the clone the code. They do a little change, check that the version of the maven project is a SNAPSHOT so they know they can safely run mvn deploy without causing any damage, they run mvn deploy, and BOOM, they accidentally deployed to production.
* Deploying the artifacts to a repository, and running them, are two separate steps. Look at our own build for the Kalix platform, we consider them separate steps, and the fact that they are separate is an important part of a CD, it allows us to run the same scripts to build the artifacts regardless of environment, but still deploy to different environments, or multiple environments, or not deploy at all and allow something else to handle deploying. But, by combining them the way we have, we leave no way for the developer to separate them.

Of course, it's very convenient to be able to deploy using mvn deploy. But, it should be opt-in, clear that that's what's happening, and clear how to turn off. Also, it should be precise. The project you're deploying to should be explicitly specified in the pom file, to prevent accidentally deploying to the wrong environment. If a user changes their current project using the kalix command, they won't necessarily expect that to affect the outcome of running a maven command (afterall, build tools like maven are supposed to be agnostic of the environment they are run on, you're meant to be able to rely on that).

So here are my suggested changes:

* Modify the maven archetype to plugin to prompt for the project to deploy to, if possible, defaulting to the currently configured kalix project (while we're at it, we can make it prompt for the docker repository to deploy to too, so users don't have to go back to the pom to update that immediately after generating a project). It should also be possible to select no project. If no project is selected, no deployment is done.
* Add a property which occurs high up in the pom that turns on/off kalix deployment. Add a comment describing what this property does, so it's clear.

**Comment by ennru** [comment]
Fixed with #1488
