### ISSUE TITLE
Release Kalix Java/Scala SDKs

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1131]
# Release Kalix Java/Scala SDKs

### Prepare

- [x] Make sure all important PRs have been merged
- [x] Check that the [latest build](https://app.circleci.com/pipelines/github/lightbend/kalix-jvm-sdk) successfully finished
- [x] Make sure a version of the proxy that supports the protocol version the SDK expects has been deployed to production

You can see the proxy version on prod [on grafana](https://lightbendcloud.grafana.net/d/2n4jVuw7z/prod-kalix-metrics?orgId=1) or using [various other methods](https://github.com/lightbend/kalix/wiki/Versioning-and-how-to-determine-what-version-is-running).

### Cutting the release 

- [x] Edit the [draft release notes](https://github.com/lightbend/kalix-jvm-sdk/releases) and create the appropriate tag
    - CI will automatically publish to Sonatype OSSRH (Maven Central) based on the tag
    - CI will update the docs/kalix-current branch

### Check availability

- [x] Check that [`docs/kalix-current`](https://github.com/lightbend/kalix-jvm-sdk/commits/docs/kalix-current) has been updated
- [x] Check the release on [Maven Central](https://repo1.maven.org/maven2/io/kalix/kalix-scala-sdk-testkit_2.13/)

### Fix and publish docs

- [ ] ~In case there were important updates, update the [supported version in the main docs](https://github.com/lightbend/kalix-docs/blob/main/docs/modules/ROOT/partials/include.adoc#L21) (affects [Supported Languages]\ (https://docs.kalix.io/reference/supported-languages.html))~
- [x] Add an item to the [Release Notes](https://github.com/lightbend/kalix-docs/blob/main/docs/modules/release-notes/pages/index.adoc) in the documentation
- [ ] ~Release the Kalix documentation to get the SDK docs updates published~

### Update to the latest version
 
- [x] Update the sdk version in samples and maven plugin
    - [x] Update the `kalix-sdk.version` in the `samples/*/pom.xml` files to the released version.
    - [x] Update the `kalix-sdk.version` default value in the `samples/scala-*/project/plugins.sbt` files to the release version
    - [x] version in `maven-java/**/pom.xml`
 
### Check docs update

- [x] Check for [updated docs](https://docs.kalix.io/index.html) (see the timestamp on the bottom of the page)

### Announcements

- [ ] Announce in [the forum](https://discuss.kalix.io/)
  - tag with releases and announcement
- [x] Inform Lightbend marketing and engineering if it's a noteworthy release
- [ ] Close this issue

**Comment by efgpinto** [comment]
@octonato @ennru what do we do regarding the post in the discussions forum? we skipped for 1.0.7, but maybe we should do a post there for 1.0.8? in a similar note to what we added for the release notes?

**Comment by octonato** [comment]
I had suggested to start blogging about the Spring SDK, but @beritou pointed out that it's maybe better to first get some feedback from a few selected users before we start to announce it to a broader audience. 

If we follow this line, than we should not include it in the discuss forum announcement. 

@beritou, any thoughts?

**Comment by efgpinto** [comment]
I'll close this and assume we might want to skip posting about this one on the forums. (Although I think it could be good to post something there as the forum has been rather quiet lately.)
