### ISSUE TITLE
Reintroduce ignore/noReply effect

### ISSUE THREAD

**Issue by johanandren** [lightbend/kalix-jvm-sdk#1169]
In #844 we removed the `NoReply` effect because we couldn't figure out when it is useful, and it is weird when used as an effect for a regular request-response action call.

Currently you can only ignore events on a message type level, ignoring a specific message type or ignoring all unknown message types, making the consumption of the event in continue for unknowns rather than stop and stay stuck until you deploy a new version supporting the message type.

While working on #1167 we realized that for usage with eventing in and out on the same method, so for example subscribing to events from an event sourced entity, transforming, and then publishing to a message broker, ignoring on a more fine granular level makes sense internally (based on the classes accepted by the spring action). There already is room for this in the protocol, with an `ActionResponse(ActionResponse.Response.Empty)`.

I think such a more fine granular level could make sense also for other types of eventing. 

Just to make one example: "publish shopping cart updates to this kafka topic, but only once they reach $100 so we can trigger a coupon to that customer", while ignoring and moving on with the source event stream for other updates.

We'd still need to handle the empty case for regular better in the proxy, maybe we could just turn that into 404/NotFound for HTTP/gRPC and filter such responses out from streaming replies.

**Comment by patriknw** [comment]
Seems like this is done?
