### ISSUE TITLE
Spring-sdk: support for streamed calls in KalixClient

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1172]
Currently, streamed calls are not supported when using the KalixClient. The underlying implementation used for the async execution assumes a body is returned:

```scala
        webClient.flatMap {
          _.post()
            .uri(uriStr)
            .bodyValue(body)
            .retrieve()
            .bodyToMono(returnType)
            .toFuture
            .asScala
```

In this case, we'll probably need to check the returning type of the `DeferredCall` being composed and understand if this needs to return a `Mono` or a `Flux`.

Haven't tested what happens when using the same as an actual `DeferredCall` but some work might be needed there as well.

**Comment by octonato** [comment]
Not needed if we implement https://github.com/lightbend/kalix-jvm-sdk/issues/1335

**Comment by efgpinto** [comment]
Closing since KalixClient is now deprecated in favor of the new type-safe ComponentClient.
