### ISSUE TITLE
Should ViewId be called ViewType ?

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1237]
I think `@ViewId` should be renamed to `@ViewType` so it is aligned with the `@EntityType` since both serve a similar purpose and have the same semantics. Right?

**Comment by johanandren** [comment]
While I agree it's a bit weird with the mismatch I think we should either change it across the SDKs, proxy and protocols, or just live with the discrepancy, not change it only in the spring SDK and have another layer of inconsistency.

Lots of previous backs and forths around the terminology, for example here: https://github.com/lightbend/kalix-proxy/pull/107

**Comment by efgpinto** [comment]
> While I agree it's a bit weird with the mismatch I think we should either change it across the SDKs, proxy and protocols, or just live with the discrepancy, not change it only in the spring SDK and have another layer of inconsistency.

Ok, yeah, I naively assumed this could be a springsdk-only thing. I now see the same for java/scala sdk. Don't know about the proxy/protocols because haven't looked there but agree with keeping consistency at the user surface at least.


> Lots of previous backs and forths around the terminology, for example here: [lightbend/kalix-proxy#107](https://github.com/lightbend/kalix-proxy/pull/107)

Reading that led me to [this](https://github.com/lightbend/kalix-proxy/issues/319) and [this](https://github.com/lightbend/kalix-proxy/issues/654). Definitely didn't mean to open such a can of worms :D ... although, still feels confusing from a dev perspective so not really sure what a reasonable path forward could be.

**Comment by ennru** [comment]
While we might think naming could have been better, we won't change it anymore.
