### ISSUE TITLE
Provide view query access through components

### ISSUE THREAD

**Issue by johanandren** [lightbend/kalix-jvm-sdk#1257]
For composing view query results with other logic in actions.

See my note in: https://discuss.kalix.io/t/how-to-use-views/144

**Comment by octonato** [comment]
I just did a quick verification and strange enough we do generate the component client, but not for all views. 

You can test it with `samples/scala-customer-registry-quickstart`. 

Compile it and go inside the Customer Value Entity. The components is providing access to `CustomerByEmailView', but not to `CustomerByNameView`.

```scala
trait Components {
 import Components._

 def customer: CustomerCalls
 def customerByEmailView: CustomerByEmailViewCalls

}
```

**Comment by johanandren** [comment]
Can it be because it is streaming perhaps?

**Comment by johanandren** [comment]
Support for streaming deferred calls: #674

**Comment by octonato** [comment]
Yep, that's it. `CustomerByNameView` query results are streamed, `CustomerByEmailView` not.

**Comment by johanandren** [comment]
Closing as this is not the actual issue.
