### ISSUE TITLE
ClassCastException when using ReplicatedCounterMap in Scala SDK

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1289]
This was reported by a user on Discuss forum. 
https://discuss.kalix.io/t/weird-error-when-retrieving-replicated-entity/159

I was able to reproduce it using the counter map we have in our [samples](https://github.com/lightbend/kalix-jvm-sdk/tree/main/samples/scala-replicatedentity-examples) which is similar to what the user was doing. 

The problem is that I was able to reproduce it only once. After restarting the service the issue went away. I was running it locally with sbt and I suspect that there are some classpath issues. The exception contains the text `... are in unnamed module of loader 'app'`. 

What doesn't make sense to me is that first command succeeds (Increase counter), while calls to Get fails.

**Comment by efgpinto** [comment]
Was able to reproduce now, this issue actually happens for Get and Increase (and probably any other), we just need to wait for passivation to come in. As the default is 30s, doing something like the below (i.e. sleeping 35 secs after the 1st command) will trigger the issue on the second attempt:

```shell
 ➜  while :; do grpcurl -plaintext -d '{"counter_map_id":"c11", "key":"hello", "value":10}' localhost:9000 com.example.replicated.countermap.CounterMapService/Increase; sleep 35; done
{

}
ERROR:
  Code: Unknown
  Message: Entity terminating
```

I'm not too acquainted with this RE piece but now with this info, shouldn't be too hard to fix I hope.

**Comment by pvlugter** [comment]
The TCK should already cover reactivation of replicated entities, but looks like the Scala SDK TCK implementation doesn't include replicated entities — could be useful to add these for test coverage.

**Comment by pvlugter** [comment]
Unimplemented TCK for Scala SDK tracked by #683.

**Comment by maristi** [comment]
Hi, any idea when this fix might go out? afraid holidays are coming up and there might not be much progress until Jan, and It's going to start blocking me from releasing a beta of my service soon.

Alternatively, is there any workaround? like using a bunch of of separate ReplicatedCounters instead of a single ReplicatedCounterMap?

**Comment by maristi** [comment]
> Hey @maristi,
> 
> I expect to have the fix released until the end of this week (16/12).

Great to hear that! thanks @efgpinto

**Comment by efgpinto** [comment]
@maristi the fix is released now in https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.1.4 .

**Comment by maristi** [comment]
> @maristi the fix is released now in https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.1.4 .

Excellent! thanks very much @efgpinto I will give it a try soon
