### ISSUE TITLE
Spring SDK: propagate metadata when handling events for ES entities

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1290]
There is no metadata available here. We need to check if we have metadata where we call `handleEvent` and is positive, we need to see how it can be propagated further.

_Originally posted by @octonato in https://github.com/lightbend/kalix-jvm-sdk/pull/1288#discussion_r1031477840_

**Comment by aludwiko** [comment]
I wanted to fix it, but I'm not sure where the problem is. There is no metadata (except enitityId and seq number) for event handlers for ES entities in the protobuf protocol itself. I think it's problematic to achieve it in case we persist many events in one batch.
