### ISSUE TITLE
Async effect does not compose with ignore

### ISSUE THREAD

**Issue by johanandren** [lightbend/kalix-jvm-sdk#1318]
If you do something like `effects.asyncEffect(Future.successful(effects.ignore))`
it tries to copy side effects but ignore does not allow that.

<img width="812" alt="screen_shot_2022-12-08_at_7 57 34_am" src="https://user-images.githubusercontent.com/666915/206452853-09f132ff-b448-476a-b870-1af83ead1024.png">

**Comment by coertel-yw** [comment]
Somewhat related: The testkit does not expose `isIgnored` or similar to test effects
