### ISSUE TITLE
Native Spring SDK components

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1323]
The Spring SDK relies on the Java SDK for the components. That means that when implementing a component, users need to import classes from `kalix.javasdk`. 

That's not bad in itself, but we are constraining the Spring users to the limitations of the Java SDK.

For example, the Java SDK was designed to be used with gRPC. In gRPC, we can't have type hierarchy and therefore we can't define typed event handlers. In the Java SDK, event handlers are all of type `Object`. 

If we had a native Spring SDK EventSourcedEntity, we could have two type parameters, like in `EventSourcedEntity<Event, State>`. This would allow us to check that events handlers are all complying with `Event`. We could even do it at compilation type if we use an annotation processor and sealed classes from Java 17.
(arguably, the above could be done directly in Java by typing the Event to Object)

A native Spring SDK components would also allow us to have `asyncReply` based on Spring Reactor (see https://github.com/lightbend/kalix-jvm-sdk/issues/997).

**Comment by efgpinto** [comment]
One thought that occured to me while working on this... I'm not sure if we should be implementing "native SpringSDK components" or "native codefirst components" instead. The difference being, say in a year we want to do Java/JaxRS, in theory we should not need to reimplement another set of components (but we have if those are under `springsdk`).. we should be able to reuse the "spring" ones ideally. In summary, I'm wondering if the new codefirst components can/should be placed under a different package in javasdk so they can be reused for other codefirst approaches on the JVM. (I'm not entirely aware of all the implications of such scenario, happy to hear your thoughts on it.)
