### ISSUE TITLE
Spring SDK: support for components options

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1327]
gRPC SDKs have components options that can be passed to providers. Spring SDK is not supporting it yet. Main problem is that users don't have access to the providers so we need to have annotations at component level that we then translated to provider options.

**Comment by aludwiko** [comment]
Heh, I almost finished with adding the passivation strategy but then I've realized that:
```
// Note: passivation strategy settings for value entities and event sourced entities are ignored.
``` so I'm skipping this option to focus only on `forwardHeaders`.

**Comment by aludwiko** [comment]
I still think that it will be good to (at least) discuss passivation strategy in terms of workflows. https://github.com/lightbend/kalix-proxy/issues/1810

**Comment by aludwiko** [comment]
A question about deferred calls. I've noticed that for deferred calls we are not passing metadata for the call. It's an empty list for grpc or http calls. I would expect that a deferred call will have the same metadata information as the origin request.

**Comment by johanandren** [comment]
I don't think that can be automatic in general, many of the metadata attributes for the incoming request is specific to that request (think of content-type or ce-subject) and not at all suitable to pass along, I think that forwarding may be better off as something the user does explicitly. 

I think we may be missing a `withMetadata` for that on the `DeferredCall`s though (and if we want to support it for timers as well it would need adding support in the proxy, actually persisting the metadata)

**Comment by aludwiko** [comment]
`withMetadata` sounds good
