### ISSUE TITLE
Spring Docs: Event Sourced Entity Quickstart

### ISSUE THREAD

**Issue by beritou** [lightbend/kalix-jvm-sdk#1343]
See https://docs.kalix.io/java/quickstart/sc-eventsourced-entity-java.html for an example

Quickstart should be discoverable via `kalix quickstart list`.

**Comment by octonato** [comment]
I've been working on this, but for now I'm completing the quickstart to the Value Entity Customer Entity. So, not yet the Event Sourced one. 

Next on the line will be the event sourced shopping cart.
