### ISSUE TITLE
Create a Kalix Spring Boot Starter

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1345]
SpringBoot has a framework to allow integrators to provide '[starters](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.developing-auto-configuration.custom-starter)'. 

> A typical Spring Boot starter contains code to auto-configure and customize the infrastructure of a given technology

For example, through starters one can decide if the http backend should be tomcat or netty. 

So var, we have hacked around a solution to not let Spring start it's own web server and then force the Kalix one (akka-http) to start. 

It will be better to revisit our code and instead build a `kalix-spring-boot-starter` that plug-ins into Spring Boot and replaces netty by akka-http + plus all the necessary code to start Kalix.

**Comment by franciscolopezsancho** [comment]
By doing this 
- we may move @KalixConfiguration to be passed through params when starting the Spring server 
- we can start the application in one go when running in local by starting testcontainers directly

**Comment by octonato** [comment]
One other advantage of having our own starter using testcontainers, is that we can easily support [auto-reload](https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html#using-boot-devtools-restart).

Auto reload isn't working today for two reasons: 

1. We need to hook the akka http lifecycle to it. Currently, it will try to start the http server again and we get a "Address already in use" error.
2. Even if we solve the above, the proxy won't do a discovery call again.

**Comment by octonato** [comment]
This is implemented in #1459. 

Auto-reload is more complicated and will be implement in follow-up PRs. I will open ticket about it.
