### ISSUE TITLE
Spring ACL annotations should use http status code 

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1348]
This is something that I didn't realise before. The deny code are gRPC codes. I think we can leave it as it for now, but we may want to change it to http status code and then convert to proto under the hood.

_Originally posted by @octonato in https://github.com/lightbend/kalix-jvm-sdk/pull/1195#discussion_r1000582808_

**Comment by octonato** [comment]
also related to https://github.com/lightbend/kalix-jvm-sdk/issues/1323

**Comment by franciscolopezsancho** [comment]
Done in https://github.com/lightbend/kalix-jvm-sdk/pull/1406
