### ISSUE TITLE
Spring SDK: support timestamps in Views

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1391]
Split from https://github.com/lightbend/kalix-jvm-sdk/issues/1336

**Comment by efgpinto** [comment]
I've spent some time trying to address this, so here are some notes:

The current main problem is when creating the descriptors. Assuming we have a Java POJO such as:
```java
public record Test(String value, Instant ts) {
}
```
We do 2 steps to get those into PB descriptors:
1. we use `ProtobufMapper` from [FasterXML/jackson-dataformats-protobuf](https://github.com/FasterXML/jackson-dataformats-binary/tree/2.15/protobuf) to map those POJOs into a ProtobufSchema
2. we manually convert that ProtobfSchema to PB descriptors

However, as reported [here](https://github.com/FasterXML/jackson-dataformats-binary/issues/349), on the first step the lib transforms any `Instance` into `double` and for that reason, on step 2 we cannot transform the field into a `google.protobuf.Timestamp` which would be the end goal. (I've tried matching by name on the original POJO and if `type == Timestamp` then harcode. The problem there is that it's a rabbit hole because you can have nested classes as well and it quickly turns into a nightmare.)


Also worth noting that the current behavior will happily take a `Instance` attribute on the POJO but if you then you will not be able to consume that on a view under the same format. It will be automatically converted to a string format and delivered to the view who will be expecting a `double` instead.

**Comment by octonato** [comment]
How hard it will be to add support for in the original library? I think that at the end, it's our best option. Of course, we will need to wait for a release, but I don't see how we could fix it otherwise.

**Comment by efgpinto** [comment]
> How hard it will be to add support for in the original library? I think that at the end, it's our best option. Of course, we will need to wait for a release, but I don't see how we could fix it otherwise.

Yeah, I'm not too sure what effort is involved. I can try to have a look at that. But according to the maintainer, one might need to address something else first:
> One practical blocker might be that the underlying protoc parser this module uses should probably replaced first (see https://github.com/FasterXML/jackson-dataformats-binary/issues/121). I suspect this might be necessary to find relevant metadata, unless this is actually something specified by Protobuf spec.

**Comment by octonato** [comment]
Yeah, I saw it but didn't understand why the parser could be a problem.
