### ISSUE TITLE
Spring SDK: mvn spring-boot:run binding

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1393]
We are binding the http server to `0.0.0.0` if the app is started with `mvn exec:exec`. However, When using `mvn spring-boot:run` (which is what we recommend on the READMEs) it binds to `127.0.0.1` and this does not work on all platforms (e.g. Linux) making the UF unreachable to a containerized proxy.

**Comment by efgpinto** [comment]
Adding `kalix.user-function-interface = "0.0.0.0"` to the `application.conf` solves the issue but I'm wondering if there's another solution that does not imply setting that explicitely (i.e. for all samples and mvn plugin).

**Comment by octonato** [comment]
I think it can be solved when we implement https://github.com/lightbend/kalix-jvm-sdk/issues/1345

The idea in #1345 is to use a Spring Boot starter to bootstrap the service the way we want. The current solution is kind of a hack, to be honest. 

If we can have more control in how we start it, we can then make `mvn spring-boot:run` bind on `0.0.0.0`.
