### ISSUE TITLE
Spring SDK: Bug? deny all traffic

### ISSUE THREAD

**Issue by franciscolopezsancho** [lightbend/kalix-jvm-sdk#1408]
`@Acl(deny = @Acl.Matcher(principal = Acl.Principal.ALL))` would deny all traffic but that is not the case. We get a 200 OK instead of 403 Forbidden.
I can see the proto descriptor is well formed but the functionality is not there.

**Comment by octonato** [comment]
Where have you tested it? In Prod? 

If you run it in dev-mode, ACLs are disabled by default to make it more convenient for local tests. More info here: https://docs.kalix.io/concepts/using-acls.html#_local_development_with_acls

**Comment by octonato** [comment]
@franciscolopezsancho, I just found out that the Spring SDK docs about ACL is wrong. 

This section https://docs.kalix.io/spring/access-control.html#_local_development_with_acls is saying the opposite of https://docs.kalix.io/concepts/using-acls.html#_local_development_with_acls

I created an issue for it: https://github.com/lightbend/kalix-jvm-sdk/issues/1409

Maybe something that you could fix in the current PR you are working on?

**Comment by franciscolopezsancho** [comment]
Nice. Yep, that must be. I'll change my current PR yes.

**Comment by franciscolopezsancho** [comment]
I did some further testing and it turns out that it was the mvn archetype that was setting `ACL_ENABLED = 'false'`.  
I tested again with true and worked as expected but then I tested it commenting the property `ACL_ENABLED` and it was turned on by default. I made sure to delete the previous docker instance of the proxy, just in case. 
Bottom line, I think https://docs.kalix.io/concepts/using-acls.html#_local_development_with_acls is wrong. 

And now I just check the [source](https://github.com/lightbend/kalix-proxy/blob/56dd38682a7013f183f57f4ea87e544ffc016397/proxy/core/src/main/resources/reference.conf#L79)  and it is enabled by default. 

I'll change the `kalix-docs` instead then, ok? @octonato

**Comment by franciscolopezsancho** [comment]
for reference https://github.com/lightbend/kalix-jvm-sdk/pull/1406

**Comment by franciscolopezsancho** [comment]
I'm looking at `dev-mode.conf` and there is no ACL disabling in there. I understand the composed config is enabling ACL even in dev-mode by inheriting it from the `reference.conf`. Could you help me to find where it gets disabled, please?

**Comment by octonato** [comment]
We have covered it in a call, but leaving it here for the record in case someone look for this info in the future. 

The `dev-mode.conf` file doesn't overwrite this config. Instead, we pass an env variable in the docker-compose that sets it to `false`.
