### ISSUE TITLE
Spring Docs: Conflicting information about ACLs 

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1409]
We have a generic page about ACL that explains that, by default, it's disabled for local development. 
https://docs.kalix.io/spring/access-control.html#_local_development_with_acls

We have changed it recently in: https://github.com/lightbend/kalix-docs/pull/1568

In the Spring SDK documentation, we have copied the same section from the main docs, but it was not updated. It still mentions that it's enabled by default.

**Comment by franciscolopezsancho** [comment]
done in https://github.com/lightbend/kalix-jvm-sdk/pull/1406
