### ISSUE TITLE
failed: SpringSdkIntegrationTest - searchUsingInstant

### ISSUE THREAD

**Issue by patriknw** [lightbend/kalix-jvm-sdk#1438]
https://app.circleci.com/pipelines/github/lightbend/kalix-jvm-sdk/5513/workflows/df7d0bc2-d272-4792-807a-c3acb3988dfb/jobs/104201?invite=true#step-109-431

```
[error] Test com.example.wiring.SpringSdkIntegrationTest.searchUsingInstant failed: org.awaitility.core.ConditionTimeoutException: com.example.wiring.SpringSdkIntegrationTest expected <0> but was <1> within 20 seconds., took 20.258s
[error]     at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
[error]     at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
[error]     at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
[error]     at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:691)
[error]     at com.example.wiring.SpringSdkIntegrationTest.searchUsingInstant(SpringSdkIntegrationTest.java:553)
```

Also, would it be possible to silence the error log for EventSourcedEntityIntegrationTest if that is expected. 
InvocationTargetException with a null cause looks like it would be a real problem, but I don't know.
https://app.circleci.com/pipelines/github/lightbend/kalix-jvm-sdk/5513/workflows/df7d0bc2-d272-4792-807a-c3acb3988dfb/jobs/104201?invite=true#step-109-460

**Comment by patriknw** [comment]
I created a separate issue for EventSourcedEntityIntegrationTest because it's actually failing, not only logging. https://github.com/lightbend/kalix-jvm-sdk/issues/1439

**Comment by octonato** [comment]
I have a fix for the first one. 

https://github.com/lightbend/kalix-jvm-sdk/pull/1440

Test was wrong, but strange enough it passed on the PR that introduced it.

**Comment by patriknw** [comment]
It's still failing. I rebased and searchWithInstant failed https://app.circleci.com/pipelines/github/lightbend/kalix-jvm-sdk/5526/workflows/00e9adc3-4763-4dce-902c-e1297ddc777f/jobs/104815?invite=true#step-109-438

**Comment by efgpinto** [comment]
Fixed in https://github.com/lightbend/kalix-jvm-sdk/pull/1455
