### ISSUE TITLE
Remove pub/sub images when not in use

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1456]
I think we talked about this, it would be good to remove or at least comment out all the google pubsub images on the docker-compose of our samples for any of those in which it is not required (which is the majority I believe).

**Comment by octonato** [comment]
Should we also comment it out in the templates? I would prefer to do so. My feeling is that this is not used in most cases or its usage is delayed until later in the development cycle. 

Ideally, if someone start to use topics in dev-mode, we should present them with a clear message and a link to some documentation explaining how to enable it for local development. 

Another option is to provide a few docker-compose variants. 

One with only the proxy using the default name (ie: `docker-compose.yml`) 
And then one `docker-compose-pubsub.yml` and one `docker-compose-kafka.yml`. The user can then choose what to do. Eventually dropping all the others they don't use.

**Comment by efgpinto** [comment]
> Should we also comment it out in the templates? I would prefer to do so. My feeling is that this is not used in most cases or its usage is delayed until later in the development cycle.

I think so. I would probably have it commented out on the templates as well.

**Comment by octonato** [comment]
what about having three docker-compose files and user pick the one they prefer?

**Comment by efgpinto** [comment]
I don't have a strong opinion tbh, I just thought that with the different docker files you would maybe need to explain somewhere that to run a specific non-standard file one needs to do `docker-compose -f file.yml up` (or delete and rename of course).. thus, having it commented with a note on the readme seemed like a simpler approach. But again, no strong feelings about it.

**Comment by octonato** [comment]
Correct, that would require more explanation. I would add it to the README to start with. 

We can add comments to the docker file, but then there is two places that need to be commented.  

I'm not sure what will be the best. We experiment and see which option feels easier.

**Comment by johanandren** [comment]
I'd vote for one file, comment out the pubsub container and parameter, and keep it as default compose file.

**Comment by ennru** [comment]
Fixed with #1476
