### ISSUE TITLE
Build docker images with `mvn install` instead

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1471]
I noticed today that we are building the docker image each time we run integration tests on any Kalix Maven project. 

The reason for that is we attached the `build` goal to the `package` phase when configuring the fabric8 plugin. 

By default, fabric8 plugin attach `build` to `install`. And that makes sense. Maven documentation describes `install` as: 

> install the package into the local repository, for use as a dependency in other projects locally

Somehow relates with #1058, in the sense that we are redefining a maven concept that can be surprising to users. Although #1058 is even worst because dangerous.

**Comment by efgpinto** [comment]
Fixed in https://github.com/lightbend/kalix-jvm-sdk/pull/1472
