### ISSUE TITLE
Missing Spring SDK samples in quickstart

### ISSUE THREAD

**Issue by franciscolopezsancho** [lightbend/kalix-jvm-sdk#1474]
https://docs.kalix.io/quickstart/prebuilt-samples.html doesn't have any reference to any Java SDK sample. (Formerly Spring SDK)

**Comment by franciscolopezsancho** [comment]
We probably want to categorize differently the `Container Image URL` to distinguish between Java (Spring) and Java/grpc.

**Comment by franciscolopezsancho** [comment]
Also version are out of wack

**Comment by efgpinto** [comment]
This one was for pre-built samples, so it was actually not done yet.. added those now in https://github.com/lightbend/kalix-docs/pull/1737 anyway
