### ISSUE TITLE
Unable to create ESE views when ESE EntityType contains hyphen 

### ISSUE THREAD

**Issue by mckeeh3** [lightbend/kalix-jvm-sdk#1475]
At runtime event sourced entity views fail at runtime with an exception: `"KalixSyntheticMethodOnShopping-cart" is not a valid identifier` for an ESE `@EntityType("shopping-cart")`.

ESEs with hyphens in the entity type works fine. The problem happens when adding views to the ESE.

The current workaround is to remove the hyphens from the entity type, e.g. `@EntityType("shoppingCart")`.

**Comment by octonato** [comment]
The error message is quite confusing. I need to check, but I think that the problem here is the generation of the synthetic method.
