### ISSUE TITLE
fix: incorrect documentation on Handling Serialization

### ISSUE THREAD

**Issue by franciscolopezsancho** [lightbend/kalix-jvm-sdk#1497]
On https://docs.kalix.io/spring/serialization.html#_receiving_cloudevents
It states that we should pass full qualified name `ce-type = fully qualified name (e.g. com.example.ValueIncreased)` but that's not the case. We are using the `non-qualified` name. 

See [here](https://github.com/lightbend/kalix-jvm-sdk/blob/30c31dbf984975c4ec55dfad199651346a19509d/sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JsonMessageCodec.scala#L56-L59) and [here](https://github.com/lightbend/kalix-jvm-sdk/blob/30c31dbf984975c4ec55dfad199651346a19509d/sdk/java-sdk-spring/src/main/java/kalix/javasdk/annotations/TypeName.java#L27-L28)

**Comment by johanandren** [comment]
There is a (I think) reasonable fixme there about using the FQN from getName though. Better fix logic than docs?

**Comment by franciscolopezsancho** [comment]
I remember discussing that one of the benefits of having the simple-name is to be able to refactor the classes into other packages seamlessly. Could you elaborate on why the FQN could be a better solution @johanandren, please?

**Comment by johanandren** [comment]
I don't know how Jackson can auto-deserialize if it isn't a FQN and the classpath contains a class matching that, how would it know where to look for a class/method to choose? 

Maybe there is a way to handle that in the Java SDK that I don't know of?

**Comment by franciscolopezsancho** [comment]
Yes. There is a way we handle that in the Java SDK. We store the relation 'class to simple-name' in a cache and then we use it to find which class/method we need. [Here](https://github.com/lightbend/kalix-jvm-sdk/blob/30c31dbf984975c4ec55dfad199651346a19509d/sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/CommandHandler.scala#L46) for example.

**Comment by octonato** [comment]
This issue is not valid anymore. Or better said, we reverted to using FQN instead of changing the docs. 

This was done here https://github.com/lightbend/kalix-jvm-sdk/pull/1562
