### ISSUE TITLE
Improve docker image lifecycle in kalix:run

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1579]
`kalix:run` is using testcontainers to bootstrap Kalix Proxy, but testcontainers was conceived for testing purposes. 

One of the issues we have is that testcontainers is designed to use random ports each time. For the moment, we are forcing the port to 9000. For our use case, it makes sense, but we are probably abusing testcontainers. 

When we restart the application, we need to wait for testcontainers to remove the previous container and free the port. This process can take long (about 5 seconds). This might be a side-effect of how testcontainers was originally designed. Since by default they use random ports, they don't care if an old container is still running. Next run will be on a new port and therefore there will be no conflict. 

On the other hand, we don't really need testcontainers inside `kalix:run`. What we need is the means to start a docker container and attach its lifecycle to the lifecycle of the process running `kalix:run`. 

Testcontainers uses https://github.com/docker-java/docker-java themselves. An alternative for us might be to use docker-java directly. As such, we can have better control over the container lifecycle.

**Comment by octonato** [comment]
We have also discussed the possibility to run a tiny http proxy on port 9000 that forwards all incoming requests to kalix-proxy running on a random port chosen my testcontainers. 

When we restart kalix:run, we can easily restart the http proxy and point it to the next random port we get from testcontainers.

**Comment by aludwiko** [comment]
I haven't analyzed it, but if the tiny proxy is necessary only to trick testcontainers, then it sounds more reasonable to use docker-java instead.

**Comment by aludwiko** [comment]
I think we can close it, we are not using test containers anymore for the kalix:run command.
