### ISSUE TITLE
Action VE Subscription at type level not supported

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1610]
Currently, if one uses an action to subscribe to a ValueEntity and places the annotation at type level, it does not work but the application will happily start-up without any problems. The state will not be consumed by that action though.

E.g.:

```java
@Subscribe.ValueEntity(value = CounterEntity.class)
public class CounterJournalToTopicAction extends Action {

    @Publish.Topic("counter-state")
    public Effect<Integer> onState(Integer event){
        return effects().reply(event);
    }
}
```

I think we should at least WARN the user about this or even throw an error.

**Comment by aludwiko** [comment]
Shouldn't this just work at a type level?

**Comment by efgpinto** [comment]
> Shouldn't this just work at a type level?

Maybe, at least if there is only a matching method that receives the entity state type. @octonato do you remember something about why this is like this currently?

**Comment by octonato** [comment]
I think this is just a bug. I would expect it to work the same way it works for Views. No reason to not have the same behavior.
