### ISSUE TITLE
Running docker-compose from inside KalixRunner

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1631]
We have recently extended the Kalix plugin (both sbt and mvn) to start docker-compose and therefore remove the need to start it on a separate terminal. 

However, this solution only works if users run the project using the plugin. Very often a user will simply start the application from the IDE and run the Main function directly. Also, when debugging an application, users will probably do it from the IDE and the Main function. 

When started in that way, the user function will run in 'standalone' and users will need to be aware that they need to run `docker-compose up` themselves. And to make it worst, we don't have the means to detect that the Main function was executed by hand and therefore we can't even print a warning or instruction to the users. 

One possible solution to that problem is to integrate the `DockerComposeUtils` inside the `KalixRunner`. 

The plan would be:

1. add a dev-mode config property: `kalix.dev-mode.docker-compose-file=docker-compose.yml`. Defaulting to `docker-compose.yml`, but users can change it if they want.
2. when the user function runs, we read that property and look for the file at the root of the process. If there is such a file, we know that we are in dev mode and we can start `DockerComposeUtils`
3. when the user function runs in prod, the file won't be present at the root (we only package `src/main/{resources,java,scala}`) and therefore we won't start `DockerComposeUtils`.
4. When running `mvn kalix:run` or `sbt run`, we set `kalix.dev-mode.docker-compose-file=none` as the user is explicitly asking to not start docker.
5. When running `mvn kalix:runAll` or `sbt runAll`, we leave it as is and we let the `KalixRunner` bootstrap the UF and the docker.
6. For integration tests using the Teskit, we need to set `kalix.dev-mode.docker-compose-file=none` as the proxy is managed by Testcontainers and we don't want to run docker-compose in such a case.

**Comment by aludwiko** [comment]
> 4. When running mvn kalix:run or sbt run, we set kalix.dev-mode.docker-compose-file=none as the user is explicitly asking to not start docker.

Isn't kalix:run equal to running Main from the IDE?

**Comment by octonato** [comment]
Yes, `kalix:run` is now the equivalent of running the Main on the IDE. And that's exactly the problem. We document `kalix:runAll` and we expect users to use it. As soon as they start the Main from the IDE, they won't immediately see that something is missing. 

Users will always have the option to run docker-compose by hand and then the Main. 
Btw, we kind of support the mix already. If you start docker-compose twice on the same dir, the second time won't try to start it but will attach to the running containers and start to print the logs.

Back to the main topic, if we run DockerComposeUtils behind the Main, the DX on IDE will be the same as with `kalix:runAll`. 

Then if you want to run Main, but without compose, you will need to set the property to `kalix.dev-mode.docker-compose-file=none`

**Comment by octonato** [comment]
I agree that users will need to understand the mechanics at some point, but should not be mandatory. Certainly not to start with Kalix. 

Back in the time when we didn't have an image for arm64, it was painful to start the container over and over, but that's not the case anymore. Both processes start in parallel, so the time spent in bootstrapping the proxy is negligible.
