### ISSUE TITLE
No content responses

### ISSUE THREAD

**Issue by jroper** [lightbend/kalix-jvm-sdk#1639]
It's common to return no content in REST APIs. For example, in response to a delete request, often the response will be 204 NoContent. The Spring SDK should support this idiomatically. Not sure of the best way to support this, one way could be for us to provide a `NoContent` class, eg:

```java
return effects().emit(...).thenReply(state -> NoContent.getInstance());
```

or even:

```java
return effects().emit(...).thenReplyNoContent();
```

The proxy already allows setting metadata to set a custom HTTP status code, and if that status code doesn't allow content, will not send any content in the HTTP body. This is just about creating an idiomatic way to do that in the Spring SDK.

**Comment by jroper** [comment]
Example of how this can be achieved today:

```java
    @DeleteMapping()
    public Effect<Asset> disposeOfAsset() {
        if (currentState().status() != Asset.AssetStatus.EXISTING) {
            return effects().error("Asset not found", StatusCode.ErrorCode.NOT_FOUND);
        }
        return effects()
                .emitEvent(new Asset.Event.AssetDisposed())
                .thenReply(Function.identity(), Metadata.EMPTY.add("_kalix-http-code", "204"));
    }
```

What I would rather is something to the effect of:

```java
    @DeleteMapping()
    public Effect<NoContent> disposeOfAsset() {
        if (currentState().status() != Asset.AssetStatus.EXISTING) {
            return effects().error("Asset not found", StatusCode.ErrorCode.NOT_FOUND);
        }
        return effects()
                .emitEvent(new Asset.Event.AssetDisposed())
                .thenReplyNoContent();
    }
```

**Comment by octonato** [comment]
I like the idea. 
Would it make sense to open it up and offer something more generic? 

A call to a REST endpoint may return many things. If we introduce `NoContent`, why don't we introduce `Created` and `Accepted`? And should they share a common trait like `Response`? 

Users can still return `Foo` if they want, but they could also type it to `Effect<Response>` and return `effects().theReply(Ok(foo))`.

We can have `Response` impl covering some of the 20x status code range and keep the errors in `effects().error(...)`. As such, it won't be possible to emit events and return an error, for example.

**Comment by jroper** [comment]
All good questions/suggestions.

One thing to note, we already support returning a `google.api.HttpBody` protobuf message in the proxy, which allows returning arbitrary HTTP bodies. I don't know if that's at all relevant here, if there's anything we want to use with that, but just something to be aware of in case we want it.

So one path might be to allow returning `HttpResponse`, which is a:

```java
record HttpResponse(
  HttpStatusCode code,
  Map<String, String> headers,
  Optional<HttpBody> body,
)
record HttpBody(
  String contentType,
  ByteString bytes
)
```

Underneath, this gets mapped to a protobuf method with a return type of `google.api.HttpBody`. We translate the `code` field into the `_kalix-http-code` metadata header, and the rest of the headers into metadata headers. The headers field is of course redundant since users can return metadata directly themselves, but feels more natural if we're going to have a response type to include headers in it.

So then we can have some predefined responses like `NoContent` and `Created`. We can also support redirects etc.

Is this offering too much functionality though? Or is the right level?

And, maybe an even better option would be to use the Spring boot response entity type, instead of defining our own:

https://www.baeldung.com/spring-response-entity

**Comment by octonato** [comment]
> And, maybe an even better option would be to use the Spring boot response entity type, instead of defining our own:

Could be an option for the existing SDK that is still very Spring related, but we will eventually want to have our own annotations and types. Also if we want to move forward with a Scala code-first SDK.

**Comment by aludwiko** [comment]
I forgot about this discussion, but in the meantime, I've created a simple PR with `HttpBody` as the output param support. https://github.com/lightbend/kalix-jvm-sdk/pull/1939/files 

With `HttpBody`, I have more control over the returned payload and content type, but I still think that we should extend the effect builder for basic use cases.

**Comment by octonato** [comment]
Done in #1936
