### ISSUE TITLE
Improve docs on how to subscribe to a Topic from a View

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1644]
I think we should document this somewhere. Subscribing to a topic from a view from docs looks like a super straightforward task: https://docs.kalix.io/java/views.html#topic-view, but it requires manual metadata management. There is sth about ce-subject here: https://docs.kalix.io/projects/message-brokers.html#_delivery_characteristics but it's not clear that this is required for views.

_Originally posted by @aludwiko in https://github.com/lightbend/kalix-jvm-sdk/pull/1642#discussion_r1206957207_

**Comment by efgpinto** [comment]
I think this is done now.
