### ISSUE TITLE
error when having two Action components with the same name in two different packages

### ISSUE THREAD

**Issue by aludwiko** [lightbend/kalix-jvm-sdk#1667]
action1:
```
package com.example.wallet.application;
@Subscribe.EventSourcedEntity(value = WalletEntity.class, ignoreUnknown = true)
public class NotifyAboutLowBalance extends Action {
```
action2
```
package com.example.wallet.ve;
@Subscribe.ValueEntity(WalletValueEntity.class)
public class NotifyAboutLowBalance extends Action {
```
exception:
```
2023-06-02 09:05:37,283 ERROR kalix.javasdk.impl.DiscoveryImpl - Error reported from Kalix system: KLX-00004 Unable to find service com.example.wallet.application.NotifyAboutLowBalance in the passed in descriptors.

The services found in the descriptor at discovery were:
  * com.example.wallet.api.WalletController
  * com.example.wallet.application.TransferFunds
  * com.example.wallet.application.WalletByBalance
  * com.example.wallet.application.WalletByOwner
  * com.example.wallet.application.WalletEntity
  * com.example.wallet.ve.NotifyAboutLowBalance
  * com.example.wallet.ve.WalletValueEntity
```

**Comment by octonato** [comment]
Can it be that we have a map like `Map[SimpleClassName, Descriptor]` in the code-first SDK? 

I vaguely remember we needed to keep descriptors on a Map to find them later.

**Comment by aludwiko** [comment]
It's more complex. On the sdk side, we have this change, from package + name to just a name:
https://github.com/lightbend/kalix-jvm-sdk/commit/5c9b2caa#diff-902d2d3964621479fb41d622d3fb3fcd8d07c15003d20862cc730bfe355669d1L138

Reverting SDK is not enough, the proxy must be adjusted as well: https://github.com/lightbend/kalix-proxy/blob/main/proxy/core/src/main/scala/kalix/proxy/FileDescriptorBuilder.scala#L21

Yeah, before I change anything I want to make sure that this is not a trap or sth.
