### ISSUE TITLE
Support running integration tests against real Kafka instance

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1689]
AFAIR, it is indeed impossible to run integration tests against Kafka at the moment becuase the proxy container run from the integration tests supports either the mock broker or the google pub sub (before the eventing testkit it would only support google pub sub). This is somehting we can (and should) easily change... it's just a matter of allowing that proxy to be configured for kafka as well (meaning we set a differnet eventing support method and a different port by default). But at the moment, I don't think we have configs for that.

_Originally posted by @efgpinto in https://github.com/lightbend/kalix-jvm-sdk/pull/1688#discussion_r1234148797_

**Comment by johanandren** [comment]
With the changes for Kafka auth, it should at least be easier to set Kafka up, new config key/or env var to set up what server to connect to (`kalix.proxy.eventing.kafka.bootstrap-servers`/`BROKER_SERVERS`) instead of the old full kafka client props file.
