### ISSUE TITLE
typed client - support compound entity keys

### ISSUE THREAD

**Issue by aludwiko** [lightbend/kalix-jvm-sdk#1703]
We need to decide what to do with compound keys in the code-first sdk. Either we fully support it, and then the typed client must be adjusted accordingly, or we can block it since it's not very intuitive to split it across many path segments. Any thoughts?

**Comment by aludwiko** [comment]
continuation of #1335

**Comment by franciscolopezsancho** [comment]
I tried to think in terms of advantages/disadvantages but only came up with a couple of disadvantages: Composite keys expose how the service composes the id. Leaking implementation details.  Second, If later on the service wants to change how the identifiers are formed, it won't be backward compatible.

**Comment by octonato** [comment]
I don't see a strong reason to not have it. I agree that it makes more sense for protocol-first SDK, but I don't think it's worth the effort to deprecate its support for the code-first SDK.

Could you clarify/explain what are the challenges to implementing it for the typed client?

**Comment by aludwiko** [comment]
well, it's not a big problem, if we will pass a map with names and values, instead of just values:
```
componentBuilder.forValueEntity("1","2","3")
```
vs
```
componentBuilder.forValueEntity(Map.of("key1", "1", "key2", "2", "key3", "3"))
```
