### ISSUE TITLE
workflows should allow to use HTTP StatusCode.ErrorCode

### ISSUE THREAD

**Issue by aludwiko** [lightbend/kalix-jvm-sdk#1731]

**Comment by octonato** [comment]
Not sure in which context this is happening. Do you mean the existing samples and documentation?

**Comment by aludwiko** [comment]
In the workflow effect builder you can only pass gRPC status code
```
<R> ErrorEffect<R> error(String description, Status.Code statusCode);
```
I Action, Entities you can also pass HTTP code:
```
<T> Effect<T> error(String description, StatusCode.ErrorCode httpErrorCode);
```

**Comment by octonato** [comment]
Oh, I see. That's an oversight.
