### ISSUE TITLE
Scala SDK: docker image name format for KCR

### ISSUE THREAD

**Issue by aklikic** [lightbend/kalix-jvm-sdk#1739]
When using Scala SDK, image is build using sbt-native-packager .
So I tried:
`sbt Docker/publish -Ddocker.registry=kcr.us-east-1.kalix.io `-> produces: `kcr.us-east-1.kalix.io/kalix-trial-shoppingcart-scala:latest`
`sbt Docker/publish -Ddocker.registry=kcr.us-east-1.kalix.io -Ddocker.username=klikic2` -> produces `kcr.us-east-1.kalix.io/kalix-trial-shoppingcart-scala:latest`

Both are not supported. 
Check issue: [9349 Do we want to support user/image:tag in kcr](https://github.com/lightbend/kalix/issues/9349)

`dockerAlias` default format is` [dockerRepository/][dockerUsername/][packageName]:[version]`
So I added in build.sbt:
```
val kalixProjectName = sys.props.get("kalix.project").getOrElse("kalix-trial-scala-ecommerce")
dockerAlias := dockerAlias.value.withName(kalixProjectName+"/"+packageName.value)
```

And run it with 
`sbt Docker/publish -Ddocker.registry=kcr.us-east-1.kalix.io -Ddocker.username=klikic2 -Dkalix.project=kalix-trial-scala-ecommerce`
that produced:  
`kcr.us-east-1.kalix.io/klikic2/kalix-trial-scala-ecommerce/kalix-trial-shoppingcart-scala:latest`

we need to find some more intuitive way how to tweak image name for pushing to KCR because I had to do this hack with sbt.

**Comment by octonato** [comment]
We can set `dockerAlias` using the sbt-kalix plugin. That's not a problem. 

The challenge is the project name. This is also something that users may want to edit, for example, you can have a staging project and a production project and you want it to be editable. 

A possible solution is to require that users passed `-Dkalix. project` each time they want to publish.

**Comment by efgpinto** [comment]
I was trying this out because I'm working on adding some more docs around this...

Isn't the right thing here to use the `username` to pass that info? E.g.
```shell
> sbt Docker/publishLocal -Ddocker.registry=kcr.us-east-1.kalix.io -Ddocker.username=lightbend-eng/es-service

...
#16 naming to kcr.us-east-1.kalix.io/lightbend-eng/es-service/eventsourced-shopping-cart:1.3.3-1-3ffa87c2 done
```

I understand that the fact it's called `username` on the sbt docker plugin might cause confusion but this is the docker username, it can be a username, an organization or a project within an organization (which is the case in the example below).

**Comment by aklikic** [comment]
This makes sense

**Comment by aklikic** [comment]
I beleive this is enough so IMO we can close the issue.

**Comment by octonato** [comment]
Let's keep this open until we get it in the documentation.

**Comment by ennru** [comment]
I hope this is more clear now after
- https://github.com/lightbend/kalix-jvm-sdk/pull/1885
- https://github.com/lightbend/kalix-docs/pull/1967
