### ISSUE TITLE
Improve withForwardedHeaders APIs

### ISSUE THREAD

**Issue by johanandren** [lightbend/kalix-jvm-sdk#1764]
Unfortunate return type, but maybe we should have some easier way to set these up?

              Additionally, `ActionOptions#withForwardedHeaders(Set)` does not get the intended signature but ends up returning a `ComponentOptions` rather than `ActionOptions`, requiring a cast to actually use the value.

_Originally posted by @johanandren in https://github.com/lightbend/kalix-jvm-sdk/issues/1296#issuecomment-1329018386_

**Comment by aludwiko** [comment]
This is actually fixed:
```
object ActionOptions {

  def defaults: ActionOptions = ActionOptionsImpl(Set.empty)

  private[kalix] final case class ActionOptionsImpl(forwardHeaders: Set[String]) extends ActionOptions {

    override def withForwardHeaders(headers: Set[String]): ActionOptions =
      copy(forwardHeaders = headers)
  }
}
trait ActionOptions extends ComponentOptions {

  /**
   * Ask Kalix to forward these headers from the incoming request as metadata headers for the incoming commands. By
   * default no headers except "X-Server-Timing" are forwarded.
   */
  override def withForwardHeaders(headers: Set[String]): ActionOptions
}
```

**Comment by johanandren** [comment]
I had missed that, I guess that is good enough then 👍
