### ISSUE TITLE
Docs about updating kalix cli on mac

### ISSUE THREAD

**Issue by sebastian-alfers** [lightbend/kalix-jvm-sdk#1776]
Not sure if that is me, but the [docs](https://docs.kalix.io/kalix/install-kalix.html) (for mac) say to use `brew upgrade kalix` but when I run this, I am getting:

```
$ brew upgrade kalix

Error: Formulae found in multiple taps:
       * lightbend-labs/brew/kalix
       * lightbend/brew/kalix

Please use the fully-qualified name (e.g. lightbend-labs/brew/kalix) to refer to the formula.
```

Using `brew upgrade lightbend/brew/kalix` works.

**Comment by johanandren** [comment]
Works for me without warning, is it perhaps that you have both the labs and lightbend taps in your local brew?

**Comment by sebastian-alfers** [comment]
Jea, probably an issue on my end.

**Comment by efgpinto** [comment]
For the record, works for me as well without warning.
