### ISSUE TITLE
Metadata missing in ViewContext

### ISSUE THREAD

**Issue by johanandren** [lightbend/kalix-jvm-sdk#1781]
Should be available like for the other component contexts

**Comment by johanandren** [comment]
This seems to already be the case because:

```trait UpdateContext extends ViewContext with MetadataContext```
and
```public interface UpdateContext extends ViewContext, MetadataContext```

And those are available as expected through an `updateContext()` in views, I was probably just looking at the wrong context? Or it was sorted since.

**Comment by roikonenvisma** [comment]
So if I want to get event's timestamp, I believe this is the suggested way: `updateContext.metadata.asCloudEvent.time`?
The other way would be `updateContext.metadata.get("ce-time").map(ZonedDateTime.parse)`.

**Comment by johanandren** [comment]
Yes, `updateContext.metadata.asCloudEvent.time` would be the recommended way.
