### ISSUE TITLE
Workflow's Effect.error not supporting Http Status Code

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1802]
Noticed that the Workflow APIs are not allowing for tweaking the returned Http Status code. One can only return gRPC codes. 

This is an oversight.

**Comment by aludwiko** [comment]
duplicates https://github.com/lightbend/kalix-jvm-sdk/issues/1731

**Comment by octonato** [comment]
Aha! I knew we had talked about this before, but didn't recall it was on an issue. Sorry for the noise.
