### ISSUE TITLE
Improved Effect documentation

### ISSUE THREAD

**Issue by aludwiko** [lightbend/kalix-jvm-sdk#1824]
Based on the feedback from: https://docs.google.com/document/d/1yI_J2RmeTh2-k9Dk2WPvHWfr0sRL_2ldd3_jPl6tsx0/edit
Described in more detail how we describe it with more context: https://docs.google.com/document/d/1_kiNW044JMxQLGjoVXCAN2zCCoaEiqZojhMJx8VCAYo/edit

**Comment by octonato** [comment]
A first PR to address it:
https://github.com/lightbend/kalix-jvm-sdk/pull/1869

We should also have a documentation page about it.

**Comment by beritou** [comment]
https://github.com/lightbend/akka-javasdk/pull/576
