### ISSUE TITLE
Remove reference to logback-dev-mode.xml in docker-compose

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1843]
The next Kalix Runtime release won't require the docker compose file to pass `-Dconfig.resource=dev-mode.conf` or `-Dlogback.configurationFile=logback-dev-mode.xml` to the underlying jvm.

We should therefore adapt all docker-compose files (including those in the templates). 

https://github.com/lightbend/kalix-runtime/pull/2141

**Comment by aludwiko** [comment]
Done
