### ISSUE TITLE
Run something at startup after discovery

### ISSUE THREAD

**Issue by patriknw** [lightbend/kalix-jvm-sdk#1858]
For example creating a timer at startup would not work until the runtime has made the discovery call and initialized the service.

**Comment by johanandren** [comment]
Important aspect: should it be run on every node startup, or once per deploy of a given version of the user service?

**Comment by johanandren** [comment]
For the record, on every node startup is relatively easy and can be done in SDK only, while once per service version deploy is something that needs support in protocol and runtime.

**Comment by efgpinto** [comment]
I was thinking on doing this based on the 1st heartbeat received. The sdk would trigger the "onStartup" when receiving it. Seems like the easiest way we have currently to know if discovery succeded.

Parsing logs coming from the runtime would be another option but I think it's more error prone.
This is if we want to avoid having changes on the Runtime side of course.

**Comment by johanandren** [comment]
That's not 100% safe because the runtime hits the service healthcheck in parallel with sharding getting ready, but maybe it is still good enough vs the work to add a new discovery endpoint method to signal ready (or parse logs fed from the runtime)

**Comment by efgpinto** [comment]
Some notes from live SUP brainstorming:
- should the "onStartup" be defined right on `Main` or rather as a specific `Action`?
  - within `Main` there is no access to component calls, timers, etc. Having this modelled as an Action seems a good fit.
  - Action / Action methods would be annotated so Runtime knows when to call a specific one. For now, only a type "onStartup" but could have others in future for similar "onRollingUpdate", "beforeReady", etc. 
- support similar execution guarantees than timers: action method is called by runtime when time comes and can be retried for a specific amount of time  (depending on config) until it suceeds. We should probably allow for fire-and-forget as well.

**Comment by octonato** [comment]
One thing that we didn't explicit mention. Such an action method will need to receive proto `Empty` or be a parameterless method in code-first SDK. Because the runtime can't build an specific message to it.

**Comment by ceecer1** [comment]
Westpac Architect's email description:

> Here is a simple example of the requirement to cache config/reference data:
>  
> Our entities support internal versioning. We need to be able to configure which versions are active so we can do a form of blue/green deployment.
>  
> This config data rarely changes. It applies equally to every instance of the same entity.
>  
> The only current way to provide the entity with such config data is by including it in the relevant commands. In this case it would need to be added to every single command! If that is not done correctly for each and every command then the consequences could be catastrophic.
>  
> Multiply this problem by the dozens of config/ref data in our solution and the issue becomes even worse.
>  
> A far better solution is to seed the current state of the config data once upfront as an in-memory singleton data structure (via a SeedConfigData command). This is not currently possible as there is no Initialise event/method we can use to send  the SeedConfigData command when the package is (re)loaded.

**Comment by efgpinto** [comment]
> A far better solution is to seed the current state of the config data once upfront as an in-memory singleton data structure (via a SeedConfigData command). This is not currently possible as there is no Initialise event/method we can use to send the SeedConfigData command when the package is (re)loaded.

What we are implementing on this ticket may or may not help depending on the answer to: do they know which entities they want to send the config to? Or ir it more like they want all existing entities to receive the config?

On this ticket, we will allow the user to be aware and execute something right after startup (and possibly at other times if we want to as well). So in this case, that could be used to load the config and the SeedConfigData command to same entities right after startup. But one would still have to know which entities to send it to. If they don't, then we will need to have a look at implementing some different feature.

**Comment by efgpinto** [comment]
Currently on its way to prod.

Status:
- [x] support in java/scala pb sdks
- [ ] feature support for code-first sdk
- [ ] documentation

**Comment by efgpinto** [comment]
To clarify the comment above, we still need to release the SDK before the feature is available to users.
