### ISSUE TITLE
failed: Maven sample (java-protobuf-customer-registry-kafka-quickstart)

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1873]
This seems to be failing consistently in different pipelines. [Ex1](https://github.com/lightbend/kalix-jvm-sdk/actions/runs/6930840501/job/18851439261), [ex2](https://github.com/lightbend/kalix-jvm-sdk/actions/runs/6932081991/job/18855824947?pr=1869)

**Comment by aludwiko** [comment]
I would start with increasing the timeout :)

**Comment by efgpinto** [comment]
yeah: https://github.com/lightbend/kalix-jvm-sdk/pull/1875 💯
