### ISSUE TITLE
Use Java 21 instead in samples and templates

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1904]
Investigate if there is anything blocking us to use java 21 in the samples and templates. 

I did a first quick try with the code-first SDK and it just worked.

**Comment by octonato** [comment]
It seems that Protobuf samples are still using Java 11. Not sure if oversight or we have a reason for it.

**Comment by johanandren** [comment]
Akka 2.6 is not tested with 21 (no released Akka version is yet, but for main we have nightlies on 21 across Akka modules) so there may be a problems there we don't know of.

**Comment by octonato** [comment]
Ok, I open a PR to see what CI says, but we can wait to merge it if we feel it's too early for the move.

**Comment by aludwiko** [comment]
Looking forward to the merge :)

**Comment by octonato** [comment]
Done
