### ISSUE TITLE
ACL doc page does not lead to further details

### ISSUE THREAD

**Issue by johanandren** [lightbend/kalix-jvm-sdk#1986]
The polixy_acl in the proto samples has a comment with a link to https://docs.kalix.io/security/acls.html however that page has no further links to individual SDK acl support, just some overview text, so to figure out how to get there I have to search for ACLs.

Should we improve linking in docs, or change that link in the sample protos to go directly to the ACL page for the Java/Scala proto SDKs?

**Comment by johanandren** [comment]
Also, something more weird:
```com/example/kalix_policy.proto:12:27: Error while parsing option value for "acl": Expected integer or identifier, got: "*"```

**Comment by efgpinto** [comment]
Yeah, maybe actually linking to different sdk-specific pages from that one makes sense, instead of just mentioning them but requiring the use to go find them.

**Comment by efgpinto** [comment]
Actually I think we should change both, we should add direct links on the general page but we could also link to the sdk-specific page from the policy file.
