### ISSUE TITLE
UnsupportedOperationException when using asyncEffect with CompletableFuture.completedStage SDK > 1.3.5

### ISSUE THREAD

**Issue by hithran** [lightbend/kalix-jvm-sdk#1996]
When updating from 1.3.5 to 1.3.8 my Actions that use an asyncEffect started throwing `UnsupportedOperationExceptions`, which I traced back to an issue in Scala: https://github.com/scala/bug/issues/12918

I use a CompletableFuture.completedStage at some point, which returns a MinimalStage, just as the bug describes.

Updating to Scala 2.13.13 (when released) will solve the issue
https://github.com/scala/bug/milestone/123

**Comment by johanandren** [comment]
Thanks for the investigation and detailed report. We'll make sure to bump as soon as 2.13.13 is out.

**Comment by He-Pin** [comment]
MinimalStage extends the completablefuture, so it's not light weight for now, how about change code to CompletableFuture.completedFuture before 2.13.13？

**Comment by hithran** [comment]
Fixed by https://github.com/lightbend/kalix-jvm-sdk/pull/2098
