### ISSUE TITLE
bug: why traceparent metadata in the headers is not read as tracing. 

### ISSUE THREAD

**Issue by franciscolopezsancho** [lightbend/kalix-jvm-sdk#2010]
When calling from an action to an entity the `Create` should retrieve the traceparent from the headers and join both `Action.InitializeCart -> Service.Create` in one trace.
<img width="1064" alt="Screenshot 2024-02-05 at 11 34 01" src="https://github.com/lightbend/kalix-runtime/assets/1381621/efbd1314-f0b5-4345-aab5-e4f7f2e5099b">

Metadata is added to the headers [ComponentSourceGenerator.scala](https://github.com/lightbend/kalix-jvm-sdk/blob/5e2825bbeeac7d407e49acaf6403bc5ae24a1d3d/codegen/java-gen/src/main/scala/kalix/codegen/java/ComponentsSourceGenerator.scala#L150) and from those the traceparent should be extracted.
```
             |        return addHeaders(((${messageType.fullyQualifiedGrpcServiceInterfaceName}Client) client).$commandMethod(), metadata).invoke($paramName);
```

**Comment by franciscolopezsancho** [comment]
I found it when implementing component to component in protobuf

**Comment by franciscolopezsancho** [comment]
Also in Spring

**Comment by franciscolopezsancho** [comment]
This doesn't apply anymore. 
<img width="616" alt="Screenshot 2024-07-08 at 09 11 34" src="https://github.com/lightbend/kalix-jvm-sdk/assets/1381621/9f29a79d-8aee-485f-abfa-de2397439801">

**Comment by efgpinto** [comment]
So maybe [this one](https://github.com/lightbend/kalix-runtime/issues/2369) is fixed as well? I even wonder if it was a  duplicate.

**Comment by franciscolopezsancho** [comment]
I'd say so, yes. 

Removing issues and deleting code are my favorites. I'm closing that one.
