### ISSUE TITLE
Some quickstarts still using a regular client instead of component client in integration tests

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#2028]
Found at least 2 quickstarts that still use a regular `WebClient` in integration tests, inteads of the component client.
I think we should use the ComponentClient unless there is a specific reason to use a WebClient.

Samples in need of update, [here](https://github.com/lightbend/kalix-jvm-sdk/blob/main/samples/java-spring-customer-registry-quickstart/src/it/java/customer/api/CustomerIntegrationTest.java) and [here](https://github.com/lightbend/kalix-jvm-sdk/blob/main/samples/java-spring-shopping-cart-quickstart/src/it/java/shoppingcart/cart/IntegrationTest.java).

**Comment by aludwiko** [comment]
Actually, a lot of samples use WebClient in tests, and I have some second thoughts about changing this. For instance, it might be surprising to see the `ComponentClient` in tests for samples/quickstarts that don't use it in the implementation. Would require some additional cognitive load to understand what it is, search the docs, etc., and we aimed to make them simple to digest. WDYT @ennru ?

**Comment by ennru** [comment]
I agree, these introductory examples will be easier to consume with less Kalix specifics. So let's keep the Spring `WebClient` unless the code is in a more advanced Kalix context already.
