### ISSUE TITLE
chore: upgrade the other samples to sbt 1.9.9 

### ISSUE THREAD

**Issue by franciscolopezsancho** [lightbend/kalix-jvm-sdk#2075]
I didn't even know that 1.9.9 existed. 

Maybe in follow-up PR we can upgrade the other samples.

_Originally posted by @octonato in https://github.com/lightbend/kalix-jvm-sdk/pull/2069#discussion_r1553613130_

**Comment by ennru** [comment]
Done with 
- #2084
