### ISSUE TITLE
Deprecation Warnings 'Using 'entity_type: ...' is deprecated, replace it with 'type_id: ...' on protos using `type_id`

### ISSUE THREAD

**Issue by visma-alexander-maslov** [lightbend/kalix-jvm-sdk#2166]
For al protos which already use `type_id` deprecation warning is emitted.

I think this is because of 
https://github.com/lightbend/kalix-jvm-sdk/blob/24c21b3b35d2c81591920b958c92b243b097847b/codegen/core/src/main/scala/kalix/codegen/ModelBuilder.scala#L687

most probably it needs to be changed to 
```scala
val typeId = getTypeId(entityDef.getEntityType, entityDef.getTypeId)
```

as warning comes from 
https://github.com/lightbend/kalix-jvm-sdk/blob/24c21b3b35d2c81591920b958c92b243b097847b/codegen/core/src/main/scala/kalix/codegen/ModelBuilder.scala#L788-L795

**Comment by johanandren** [comment]
Thanks for letting us know!
