### ISSUE TITLE
Use JUnit5 as default

### ISSUE THREAD

**Issue by ennru** [lightbend/kalix-jvm-sdk#41]
Update: we decided to not offer it as an option, but pick juni5.

(keeping previous description for the record)

--------------------------------------

Our Java SDK testkit supports both JUnit 4 and JUnit 5.
The current codegen generates JUnit 4 code.

We'd possibly need a configuration to allow selecting the desired JUnit style (and support for it in codegen).

**Comment by octonato** [comment]
Should we really have this as an option? 

I think it's fine to use JUnit 5 by default. If users prefer to use JUnit4 they can change their dependencies and adapt.

**Comment by ennru** [comment]
I agree with a JUnit 5 default.
The codegen and Maven archetype do JUnit 4 right now...

**Comment by ennru** [comment]
As a first step, our examples should be switched to use JUnit 5.

Java/Protobuf SDK
- [ ] java-protobuf-customer-registry-kafka-quickstart
- [ ] java-protobuf-customer-registry-quickstart
- [ ] java-protobuf-customer-registry-views-quickstart
- [ ] java-protobuf-doc-snippets
- [ ] java-protobuf-eventsourced-counter
- [ ] java-protobuf-eventsourced-customer-registry
- [ ] java-protobuf-eventsourced-customer-registry-subscriber
- [ ] java-protobuf-eventsourced-shopping-cart
- [ ] java-protobuf-fibonacci-action
- [ ] java-protobuf-first-service
- [ ] java-protobuf-reliable-timers
- [ ] java-protobuf-replicatedentity-examples
- [ ] java-protobuf-replicatedentity-shopping-cart
- [ ] java-protobuf-shopping-cart-quickstart
- [ ] java-protobuf-valueentity-counter
- [ ] java-protobuf-valueentity-counter-spring-client
- [ ] java-protobuf-valueentity-customer-registry
- [ ] java-protobuf-valueentity-shopping-cart
- [ ] java-protobuf-view-store
- [ ] java-protobuf-web-resources

Java SDK
- [ ] java-spring-customer-registry-quickstart
- [ ] java-spring-customer-registry-views-quickstart
- [ ] java-spring-doc-snippets
- [ ] java-spring-eventsourced-counter
- [ ] java-spring-eventsourced-customer-registry
- [ ] java-spring-eventsourced-customer-registry-subscriber
- [ ] java-spring-eventsourced-shopping-cart
- [ ] java-spring-fibonacci-action
- [ ] java-spring-reliable-timers
- [ ] java-spring-shopping-cart-quickstart
- [ ] java-spring-transfer-workflow
- [ ] java-spring-transfer-workflow-compensation
- [ ] java-spring-valueentity-counter
- [ ] java-spring-valueentity-customer-registry
- [ ] java-spring-valueentity-shopping-cart
- [ ] java-spring-view-store

**Comment by ennru** [comment]
The Java SDK archetypes use JUnit 5 as that's what Spring Boot does.

The Java/protobuf SDK archetypes and examples are still on JUnit 4:

https://github.com/lightbend/kalix-jvm-sdk/blob/90a41250bac8acd416bb79a8e2708758f0b23012/maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml#L290-L291

https://github.com/lightbend/kalix-jvm-sdk/blob/90a41250bac8acd416bb79a8e2708758f0b23012/maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml#L290-L291
