### ISSUE TITLE
Remove support for noReply effect

### ISSUE THREAD

**Issue by johanandren** [lightbend/kalix-jvm-sdk#718]
If you use it, it causes an error in the proxy, a call to a service should always result in a reply or a failure so we can remove the effect from the API?

Noticed by @hseeberger

**Comment by franciscolopezsancho** [comment]
I'm testing this in local with the java-eventsourced-counter, that has noReply in an Action, and I don't see any errors. Could you please elaborate further? 
Is the acceptance criteria here just removing the Effect noReply from everywhere in API? From each entity and also from Action? 
@johanandren  @hseeberger

**Comment by johanandren** [comment]
I don't remember the specific error @hseeberger saw, but even if there is no error I think it doesn't make sense. For a void type of action we use `google.protobuf.Empty` in all the samples so I think that should be the canonical way (and that also makes it visible in the descriptor that a method is a no-reply).

**Comment by franciscolopezsancho** [comment]
Makes sense to me. I'll remove `noReply` from Entities and Action, and change for  `google.protobuf.Empty` in the current examples. I'll check the docs.

**Comment by pvlugter** [comment]
Was the `noReply` for streaming?

**Comment by franciscolopezsancho** [comment]
Just to be sure. We are talking about removing ,among others, [NoReplay](https://github.com/lightbend/akkaserverless-java-sdk/blob/3fb57278574016629745753775bb70760e8d2e0e/sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/effect/SecondaryEffectImpl.scala#L82) as well, right? So, there will be no noReplay in any shape or form.

**Comment by pvlugter** [comment]
Yeah, not clear what the original intent was. The entities all have `allowNoReply = false`. Maybe it was originally for `noReply` + side effects when streaming, which is only supported by actions, as the only way to just send side effects?

**Comment by franciscolopezsancho** [comment]
Interesting. I had no idea what `allowNoReply` could be for.  Now I have one idea at least 👍

**Comment by franciscolopezsancho** [comment]
I understand this is now ready to close. Would you agree @johanandren?
