### ISSUE TITLE
Add FOSSA license and dependency checks

### ISSUE THREAD

**Issue by raboof** [lightbend/kalix-jvm-sdk#845]
In other projects we use FOSSA to help verify we don't depend on libraries whose license doesn't permit it, and to check none of the dependencies have known outstanding CVE's.

We should probably set this up here, too. Do we want to put it in GitHub Actions (like our other open source repo's) or CircleCI (like our other Akkaserverless repo's)?

**Comment by ennru** [comment]
We do this since a while back.
