### ISSUE TITLE
Provide execution context to be used by user code

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#942]
It came to my attention that we don't have an execution  context that users can use when working with Futures. 

That's mostly needed for Actions since it's the place we recommend users to deal with async calls.

We could also offer two ExecutionContext. One for general usage and one for blocking operations.

_Originally posted by @octonato in https://github.com/lightbend/kalix-jvm-sdk/pull/921#discussion_r861937779_

**Comment by johanandren** [comment]
Is there a reason they should not use the default global one in Scala?
