### ISSUE TITLE
customer-registry contains Main generated with different SDK version

### ISSUE THREAD

**Issue by raboof** [lightbend/kalix-jvm-sdk#945]
the current customer-registry has a `Main.java` with a comment with `/*`, but when you re-generate it it has a comment with `//`. We should probably make sure it's generated with the correct version of the SDK?

**Comment by octonato** [comment]
We can from time to time regenerated things just to make them resemble to a fresh project, but I don't think it's a big issue.

**Comment by raboof** [comment]
I started by checking the generated project into version control, and then when I changed the proto definition and re-generated the `Main` there were changes I didn't expect. I think it gives a more reliable feel when only the things you expect to change change ;)

Maybe we shouldn't ship a `Main` at all and just expect it to be generated on first build?

**Comment by octonato** [comment]
The problem is that we use the main in the docs. I just realised that the docs mentions the `withComponents` but shows the old way of registering. 

I have a PR to fix it. https://github.com/lightbend/kalix-jvm-sdk/pull/951

**Comment by octonato** [comment]
But I agree that for samples that are not used in the docs, we could simply not commit the main.
