### ISSUE TITLE
Use current sbt syntax in samples

### ISSUE THREAD

**Issue by johanandren** [lightbend/kalix-jvm-sdk#971]
Originally reported by @SethTisue here: lightbend/kalix-docs#1323

(nitpick, not urgent — yet worth changing, IMO)

at e.g. https://docs.kalix.io/java/quickstart/cr-value-entity-scala.html I see:

sbt docker:publish -Ddocker.username=[your-docker-hub-username]
the configuration:task style syntax is legacy from old sbt versions; for several years now Configuration/task is what sbt users learn instead

**Comment by ennru** [comment]
Are you aware of more places, or can we close this?

**Comment by johanandren** [comment]
Now it's fixed with the second PR.
