### ISSUE TITLE
Mock infrastructure for Action testkit

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#984]
The testkit doesn't allow us to test any method that makes usage of `components.someService.call(...).execute`. Any Action executing a `DeferredCall` will fail. 

This is very limiting and with the addition of Timers, it makes the testing of Timers also very limiting (as explained [here](https://github.com/lightbend/kalix-jvm-sdk/pull/965#discussion_r871778361)). 

However, we may have a simple solution to allow mocks. 

We could have a minimalistic mock API for components. That could look something like that:

```scala
val defCall: DeferredCall[In, Out] = components.someService.call(...)
val mockedCall = 
  testkit.componentMock(defCall) { In =>  // input message that's 'sent' to component
     Out // simulated component returning Out
   }
```

The user will be allowed to call `defCall.execute` inside their Action. We will complete the Future using the function `In => Out` they provide. 

Users could use `mockedCall` to verify if the call was made or not. 

This will remove the limitation we have now and allow more sensible tests for components and timers. We won't be able to cover calls to external gRPC services though.

**Comment by octonato** [comment]
How would you mock the components calls with such a mock library? Components are not accessed via their service interfaces. They are accessed via a synthetic interface produced by codegen. The one that returns `DeferredCall`. 

What you suggests will work for other gRPC calls, but not for calls to components. Users will need to mock the `ActionContext` to fake the conversion from `DeferredCall` to `Future`. And we are already passing a `TestActionContext`. 

This is not something we can expect users to replace with a mock version.

**Comment by johanandren** [comment]
Discussed a bit elsewhere, noting down what I said:

No, they'd mock the gRPC service interface, which is what they'd use if they interact with the service from outside of Kalix or from another Kalix service. A bit alien but nothing crazy.

I think the shortest path to implementing a mocking API like the suggested one might anyway be to let that produce service interface mocks that the ActionContext will pass to the `DeferrredCall` async call logic.

**Comment by octonato** [comment]
I agree that it will be better to have only one way of doing it. We can give a try with a general approach for mock. 

I do think it's quite alien though. 

Users will define a service using:

`rpc Create(CreatUser) return (Empty)`

but encode their logic using: 

`def create(state:User, cmd: CreateUser): Effect[Empty]`

call that same components using: 

`val call: DeferredCall[CreateUser, Empty] = components.users.create(CreateUser(...))`
or 
`val call: Future[Empty] = components.users.create(CreateUser(...)).execute`

But then mock something as: 

`def create(cmd: CreateUser): Future[Empty]`


Too many shapes, no clear connection about when and where to use what.

**Comment by efgpinto** [comment]
Marking this as resolved.

**Comment by efgpinto** [comment]
@octonato I marked this as resolved but then I thought that maybe we want to keep this open until we do documentation about it? Is that the usual way to go about it? Or how do you prefer?

**Comment by efgpinto** [comment]
Created a follow-up issue #1023  for docs as suggested, so closing this one.
